# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cpp_pairwise_L2 <- function(muA, muB, covA, covB) {
    .Call('_T4ecdf_cpp_pairwise_L2', PACKAGE = 'T4ecdf', muA, muB, covA, covB)
}

integrate_1d <- function(tseq, fval) {
    .Call('_T4ecdf_integrate_1d', PACKAGE = 'T4ecdf', tseq, fval)
}

cpp_kmeans <- function(data, k) {
    .Call('_T4ecdf_cpp_kmeans', PACKAGE = 'T4ecdf', data, k)
}

eval_gaussian <- function(x, mu, cov) {
    .Call('_T4ecdf_eval_gaussian', PACKAGE = 'T4ecdf', x, mu, cov)
}

eval_gaussian_data <- function(X, mu, cov) {
    .Call('_T4ecdf_eval_gaussian_data', PACKAGE = 'T4ecdf', X, mu, cov)
}

eval_gmm_data <- function(X, mus, covs, weight) {
    .Call('_T4ecdf_eval_gmm_data', PACKAGE = 'T4ecdf', X, mus, covs, weight)
}

eval_gmm <- function(x, mus, covs, weight) {
    .Call('_T4ecdf_eval_gmm', PACKAGE = 'T4ecdf', x, mus, covs, weight)
}

